dist: trusty
sudo: required

language: node_js
cache:
  directories:
    - ./node_modules/

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng test

notifications:
  email:
    on_failure: change
    on_success: change
