os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.4.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - yarn global add @angular/cli
install:
  - yarn install
script:
  - ng test --watch false
#  - ng e2e
notifications:
  email:
    on_failure: change
    on_success: change
